# Generated by Django 5.1.7 on 2025-07-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trimlyapp', '0002_alter_reservation_accepted_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intervalo_turno',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
